# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: latika
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: shopping-cart-serverless
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shopping-cart-serverless

provider:
  name: aws
  runtime: nodejs20.x
  region: ca-central-1
  endpointType: regional

functions:
  getOrders:
    handler: handler.getOrders
    events:
      - httpApi:
          path: /orders
          method: get
          cors: true
    package:
      include:
        - node_modules/**
        - package.json
        - package-lock.json
